

--1.학과 이름 계열  표시하시오

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;


--2. 학과의 학과 정원 출력

SELECT DEPARTMENT_NAME|| '의 정원은 ' || CAPACITY || '입니다.'
FROM TB_DEPARTMENT;

--3. '국어국문학과' 에 다니는 여학생 중 현재 휴학중인 여학생을 찾아달라는 요청이 들어왔다.
--   누구인가?(국문학과의 '학과코드'는 학과 테이블(TB_DEPARTMENT)을 조회해서 찾아내도록 하자)

SELECT STUDENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
      AND SUBSTR(STUDENT_SSN, 8, 1) IN ('2','4')
      AND SUBSTR(ABSENCE_YN, 1,1) = 'Y';

--4. 도서관에서 대출 도서 장기 연체자 들을 찾아 이름을 게시하고자 한다.
-- 그대상자들의 학번이 다음과 같을 때 대상자들을 찾는 적절한 SQL 구문을 작성하시오

SELECT STUDENT_NAME
FROM TB_STUDENT
--A513079, A513090, A513091, A513110, A513119
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NO DESC;

--5. 입력정원이 20명 이상 30명 이하인 학과들의 학과 이름과 계얄을 출력하시오.

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6. 
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY;

--10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1, 2) = '전주'
    AND TO_CHAR(ENTRANCE_DATE, 'YY') = '02'
    AND ;
    

