

--10. 학생일반정보 VIEW

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT;


CREATE VIEW VW_TN_STUDENTINFO
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT;

SELECT * FROM VW_STUDENT;

--11. 춘 기술 대학교는 1년에 두번씩 학과별로 학생과 지도면담한다

CREATE VIEW VW_COACH_PROFRSSOR
AS SELECT STUDENT

