CREATE TABLE PLAYER (
    PLAYERNO NUMBER PRIMARY KEY,
    PLAYERNAME VARCHAR2(20 BYTE) NOT NULL,
    PLAYERTEAM VARCHAR2(20 BYTE) NOT NULL,
    NATION
    AGE NUMBER,
    HEIGHT NUMBER,
    WEIGHT NUMBER,
    GOAL NUMBER,
    ASSIST NUMBER
 );
 
 