DROP TABLE PLAYER;
CREATE TABLE PLAYER (
    PLAYERNO NUMBER PRIMARY KEY,
    PLAYERNAME VARCHAR2(20 BYTE) NOT NULL,
    PLAYERTEAM VARCHAR2(20 BYTE) NOT NULL,
    PLAYERBACKNUM CHAR(10 BYTE) NOT NULL,
    NATION VARCHAR2(50 BYTE),
    AGE NUMBER,
    GOAL NUMBER,
    ASSIST NUMBER
 );
 
DROP SEQUENCE SEQ_PLAYERNO; 
CREATE SEQUENCE SEQ_PLAYERNO
NOCACHE;
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'호날두', '맨유', '7', '포르투갈', 38, null, null);

INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'메시', '바르샤', '10', '아르헨티나', 35, null, null); 

INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL, '손흥민', '토트넘', '7', '대한민국', 32, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'홀란드', '맨시티', '6', '노르웨이', 25, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'벨링엄', '레알', '8', '잉글랜드', 23, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'케인', '뮌헨', '9', '잉글랜드', 31, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'지루', 'AC밀란', '10', '프랑스', 36, null, null); 

INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'마르티네스', '인터밀란', '7', '아르헨티나', 24, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'오시멘', '나폴리', '9', '나이지리아', 28, null, null); 
 
INSERT INTO PLAYER
VALUES(SEQ_PLAYERNO.NEXTVAL,'루카쿠', 'AS로마', '18', '벨기에', 30, null, null); 

COMMIT;