--1.
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME LIKE '___\_%' ESCAPE '\';

--3.
SELECT PROFESSOR_NAME, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1,2), 'RRRR')) + 1 AS "나이"
FROM TB_PROFESSOR
ORDER BY 나이 ASC;


--4. 교수의 이름에 성을 제외하고 출력하기 출력헤더는 "이름" 출력
SELECT SUBSTR(PROFESSOR_NAME, 2,2) AS "이름"
FROM TB_PROFESSOR;


--5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (2024 - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RRRR')) + 1) = 20 ;


--6. 2020년 크리스마스는 무슨 요일인가
SELECT TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'DAY')
FROM DUAL;

SELECT TO_DATE('20201225', 'YYYYMMDD')
FROM DUAL;

--7.
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11','YY/MM/DD')
FROM DUAL;


--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9.

SELECT ROUND(AVG(POINT), 1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NAME = '한아름';

--10.
SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;


--11. 지도 교수 배정 받지 못한 학생의 수 COUNT(*)으로 출력

SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12. 

SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", AVG(POINT) AS "년도 별 평점" 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도 ASC;

--13 학과별 휴학생 수 학과코드명, 휴학생 수 출력
SELECT  DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
HAVING SUBSTR(ABSENCE_YN, 1, 1) = 'Y';

--14 동명이인 학생을 찾아서 동일이름, 동명인수 출력

SELECT STUDENT_NAME
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1;

--15
SELECT  SUBSTR(TERM_NO, 1, 4) AS "년도", NVL(SUBSTR(TERM_NO, 5, 2), ' ') AS "학기", (ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4) ,  SUBSTR(TERM_NO, 5, 2))
ORDER BY 년도 ASC;














