/*
SELECT * 
FROM EMPLOYEE E 
LEFT JOIN EMPLOYEE M ON (M.MANAGER_ID = E.BONUS)
AND BONUS IS NULL;
*/
/*
SELECT * FROM EMPLOYEE 
WHERE BONUS IS NULL AND MANAGER_ID IS NOT NULL;
*/


SELECT ROWNUM, SALARY, EMP_NAME
FROM EMPLOYEE
WHERE  ROWNUM <= 5
ORDER BY SALARY DESC;

SELECT SALARY, EMP_NAME
FROM EMPLOYEE
WHERE  ROWNUM <= 3
ORDER BY SALARY DESC;

SELECT EMP_NAME, SALARY
FROM (SELECT EMP_NAME, SALARY
        FROM EMPLOYEE
        ORDER BY SALARY DESC)
        WHERE ROWNUM <=3 AND SALARY IS NOT NULL;